const ofertas = [
    {
        id: 1,
        carrera: "Ingeniería Informática",
        institucion: "Institución de Educación Superior A",
        sede: "Concepción",
        area: "Tecnología",
        modalidad: "Presencial",
        jornada: "Diurna",
        duracion: "8 semestres",
        matricula: 180000,
        arancel: 3200000,
        imagen: "https://placehold.co/600x400/FFC400/171717?text=Ingenieria+Informatica"
    },
    {
        id: 2,
        carrera: "Ingeniería en Administración",
        institucion: "Institución de Educación Superior B",
        sede: "Talcahuano",
        area: "Administración",
        modalidad: "Presencial",
        jornada: "Vespertina",
        duracion: "8 semestres",
        matricula: 160000,
        arancel: 2900000,
        imagen: "https://placehold.co/600x400/FFC400/171717?text=Administracion"
    },
    {
        id: 3,
        carrera: "Enfermería",
        institucion: "Institución de Educación Superior C",
        sede: "Concepción",
        area: "Salud",
        modalidad: "Presencial",
        jornada: "Diurna",
        duracion: "10 semestres",
        matricula: 200000,
        arancel: 4100000,
        imagen: "https://placehold.co/600x400/FFC400/171717?text=Enfermeria"
    },
    {
        id: 4,
        carrera: "Técnico en Programación",
        institucion: "Institución de Educación Superior A",
        sede: "Los Ángeles",
        area: "Tecnología",
        modalidad: "Presencial",
        jornada: "Vespertina",
        duracion: "5 semestres",
        matricula: 120000,
        arancel: 2100000,
        imagen: "https://placehold.co/600x400/FFC400/171717?text=Programacion"
    },
    {
        id: 5,
        carrera: "Diseño Gráfico",
        institucion: "Institución de Educación Superior D",
        sede: "Concepción",
        area: "Arte y Diseño",
        modalidad: "Presencial",
        jornada: "Diurna",
        duracion: "8 semestres",
        matricula: 150000,
        arancel: 2800000,
        imagen: "https://placehold.co/600x400/FFC400/171717?text=Diseno+Grafico"
    },
    {
        id: 6,
        carrera: "Trabajo Social",
        institucion: "Institución de Educación Superior E",
        sede: "Chillán",
        area: "Ciencias Sociales",
        modalidad: "Presencial",
        jornada: "Diurna",
        duracion: "10 semestres",
        matricula: 170000,
        arancel: 3000000,
        imagen: "https://placehold.co/600x400/FFC400/171717?text=Trabajo+Social"
    },
    {
        id: 7,
        carrera: "Técnico en Electricidad",
        institucion: "Institución de Educación Superior B",
        sede: "Talcahuano",
        area: "Tecnología",
        modalidad: "Presencial",
        jornada: "Vespertina",
        duracion: "5 semestres",
        matricula: 110000,
        arancel: 1950000,
        imagen: "https://placehold.co/600x400/FFC400/171717?text=Electricidad"
    },
    {
        id: 8,
        carrera: "Pedagogía en Educación Básica",
        institucion: "Institución de Educación Superior F",
        sede: "Concepción",
        area: "Educación",
        modalidad: "Presencial",
        jornada: "Diurna",
        duracion: "10 semestres",
        matricula: 180000,
        arancel: 3300000,
        imagen: "https://placehold.co/600x400/FFC400/171717?text=Pedagogia"
    }
];